---
title: "Big Data"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
```


```{r big_read, cache = TRUE}
# The real data does not have the same columns as the demo data. Very annoying!
# Note you can use the n_max argument to read_csv() to just read in the first
# 100 or so rows, thereby quickly getting back the message about the column
# types. Then, we use this new listing of types. Use cache = TRUE so that you
# don't have to repeat long calculations every time you reknit the document.

x <- read_csv("~/data/census/censoc_dmf_v2/censoc_dmf_v2.csv",
                   col_types = cols(HISTID = col_character(),
                                    byear = col_double(),
                                    bmonth = col_double(),
                                    dyear = col_double(),
                                    dmonth = col_double(),
                                    death_age = col_double(),
                                    link_abe_exact_conservative = col_double(),
                                    weight = col_double(),
                                    weight_conservative = col_double()))
```


Create 1% sample of the data 

```{r}
small <- x %>% 
  slice_sample(prop = 0.01)

```


Create bar plot of dbmonth with small

```{r}
small %>% 
  ggplot(aes(x = dmonth)) +
  geom_bar()
```



```{r}
# See which months have highest deaths
small %>% 
  select(dmonth, dyear) %>% 
  group_by(dmonth) %>% 
  count() 

```

Recreate preceptor's graph

```{r}

small %>% 
  select(dmonth, dyear) %>% 
  group_by(dyear, dmonth) %>% 
  count() %>% 
  pivot_wider(names_from = dmonth,
              names_prefix = "dmonth_",
              values_from = n) %>% 
  mutate(ratio = dmonth_1 / dmonth_7) %>% 
  
  ggplot(aes(x = dyear, y = ratio)) +
  geom_point() +
  geom_smooth(method = lm,
              formula = y ~ x) +
  labs(title = "Mortality over time",
       subtitle = "Are January deaths increasing?",
       x = "year of death", y = "ratio of January to July deaths",
       caption = "Source: CenSoc")
       
  

```

